version: "3.8"
services:
  # sidecar-subtensor:
  #   container_name: sidecar-subtensor
  #   image: parity/substrate-api-sidecar:latest
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     SAS_SUBSTRATE_URL: wss://entrypoint-finney.opentensor.ai:443
