log:
  level: "DEBUG" # or "INFO"

accessLog: {} # this enables access logging with the default format

api:
  dashboard: true

entryPoints:
  websecure:
    address: ":443"
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
providers:
  providersThrottleDuration: 2s
  docker:
    exposedByDefault: false
  file:
    filename: /etc/traefik/traefik.yml
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: fabian@tentium.se
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        entryPoint: websecure

http:
  routers:
    node-subtensor:
      rule: "Host(`ws.taotensor.com`)"
      service: node-subtensor
      tls:
        certresolver: letsencrypt
      entryPoints:
        - websecure

  services:
    node-subtensor:
      loadBalancer:
        servers:
          - url: "http://172.31.28.94:9944"
